vich_uploader:
    db_driver: orm
    metadata: 
        type: attribute

    mappings:
        tricks_images:
            uri_prefix: /images/tricksImages
            upload_destination: '%kernel.project_dir%/public/images/tricksImages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
